//
//  Data+.swift
//  LSExtensions
//
//  Created by 영준 이 on 2018. 4. 23..
//  Copyright © 2018년 leesam. All rights reserved.
//

import Foundation

extension Data{
    /**
        Hex String generated by Byte Sequence of this.
    */
    public var hexString : String{
        return self.reduce("", {$0 + String(format: "%02X", $1)});
    }
}
