//
//  Double+.swift
//  pallyconswiftdemo
//
//  Created by 영준 이 on 2018. 6. 25..
//  Copyright © 2018년 leesam. All rights reserved.
//

import Foundation
import AVFoundation

extension Double{
    /**
         Returns string generated by given format with time created by this double(seconds)
         - parameter format: time format
     */
    public func dateString(_ format : String = "HH:mm:ss") -> String{
        var value = "";
        
        let date = Date(timeIntervalSince1970: self);
         let formatter = DateFormatter();
         formatter.timeZone = TimeZone(identifier: "UTC");
         formatter.dateFormat = format;
         
         value = formatter.string(from: date);
        //tries to generate formatted string with DateComponentsFormatter
        /*let formatter = DateComponentsFormatter();
        formatter.zeroFormattingBehavior = .pad;
        formatter.allowedUnits = [.hour, .minute, .second];
        formatter.unitsStyle = .positional;
        //formatter.maximumUnitCount = 3;
        if self < 3600{
            formatter.allowedUnits = [.minute, .second];
            //formatter.zeroFormattingBehavior = .default;
        }else{
            
        }
        value = formatter.string(from: self) ?? "";*/
        
        return value;
    }
    
    /**
        Generate CMTime with this
        - parameter timescale : timescale to use for making
    */
    public func time(_ timescale : CMTimeScale = 600) -> CMTime{
        return CMTimeMakeWithSeconds(self, timescale);
    }
}
